import type { PanelRoleKey } from "@/lib/domain/roles";
import type { SidebarItem } from "@/lib/types";

export const sidebarByRole: Record<PanelRoleKey, SidebarItem[]> = {
  expert: [
    {
      label: "داشبورد",
      href: "/expert",
      icon: "dashboard",
      description: "وضعیت سفارش‌های روز",
    },
    {
      label: "سفارش ها",
      href: "/expert/orders",
      icon: "shopping-cart",
      description: "فهرست سفارش‌ها",
    },
    {
      label: "مشتری‌ها",
      href: "/expert/customers",
      icon: "users",
      description: "مشتری‌ها و آدرس‌ها",
    },
    {
      label: "کالاها و قیمت‌ها",
      href: "/expert/products",
      icon: "boxes",
      description: "کالاهای قابل فروش و قیمت‌ها",
    },
    {
      label: "پیش فاکتورها",
      href: "/expert/quotations",
      icon: "file-text",
      description: "فهرست و مدیریت پیش فاکتور",
    },
  ],
  naja: [
    {
      label: "داشبورد",
      href: "/naja",
      icon: "dashboard",
      description: "وضعیت سفارش‌های ناجا",
    },
    {
      label: "سفارش های ناجا",
      href: "/naja/orders",
      icon: "shopping-cart",
      description: "ثبت‌شده و برگشتی",
    },
    {
      label: "گزارش ریالی",
      href: "/naja/reports/rial",
      icon: "file-text",
      description: "مبالغ سفارش‌های ناجا",
    },
  ],
  manager: [
    {
      label: "داشبورد",
      href: "/manager",
      icon: "dashboard",
      description: "خلاصه تصمیم‌های امروز",
    },
    {
      label: "سفارش های در انتظار تأیید",
      href: "/manager/pending-orders",
      icon: "clipboard-check",
      description: "تأیید و لغو سفارش",
    },
    {
      label: "روند سفارش ها",
      href: "/manager/order-tracking",
      icon: "activity",
      description: "روند انجام سفارش",
    },
    {
      label: "موجودی فروش و انبار",
      href: "/manager/inventory",
      icon: "boxes",
      description: "فروش و موجودی انبار",
    },
    {
      label: "ردیابی موجودی",
      href: "/manager/warehouse/stocks",
      icon: "warehouse",
      description: "کدهای رهگیری و سریال‌ها",
    },
    {
      label: "تأیید انتقال موجودی",
      href: "/manager/stock-transfers",
      icon: "truck",
      description: "درخواست‌های انتقال داخلی",
    },
  ],
  warehouse: [
    {
      label: "داشبورد",
      href: "/warehouse",
      icon: "dashboard",
      description: "نمای کلی انبار",
    },
    {
      label: "ورود کالا",
      href: "/warehouse/inbound",
      icon: "plus-circle",
      description: "ثبت ورود کالا",
    },
    {
      label: "رسیدهای ورود",
      href: "/warehouse/inbound/receipts",
      icon: "file-check",
      description: "رسیدهای ثبت‌شده",
    },
    {
      label: "ردیابی موجودی",
      href: "/warehouse/stocks",
      icon: "boxes",
      description: "کدهای رهگیری و سریال‌ها",
    },
    {
      label: "انتقال‌ها",
      href: "/warehouse/stock-transfers",
      icon: "truck",
      description: "انتقال بین انبارها",
    },
    {
      label: "خروج کالا",
      href: "/warehouse/outbound",
      icon: "package",
      description: "آماده حواله خروج",
    },
    {
      label: "حواله های خروج",
      href: "/warehouse/exit-slips",
      icon: "truck",
      description: "حواله‌ها و ارسال",
    },
    {
      label: "تحویل‌شده‌ها",
      href: "/warehouse/delivered",
      icon: "file-check",
      description: "تأیید تحویل نهایی",
    },
  ],
  finance: [
    {
      label: "داشبورد",
      href: "/finance",
      icon: "dashboard",
      description: "وضعیت مالی سفارش‌ها",
    },
    {
      label: "آماده فاکتور",
      href: "/finance/ready",
      icon: "layers",
      description: "آماده بررسی مالی",
    },
    {
      label: "فاکتورها",
      href: "/finance/invoices",
      icon: "file-text",
      description: "اسناد مالی صادرشده",
    },
    {
      label: "فاکتورهای داخلی",
      href: "/accounting/internal-invoices",
      icon: "file-check",
      description: "آماده ثبت در حسابداری",
    },
  ],
  support: [
    {
      label: "داشبورد",
      href: "/support",
      icon: "dashboard",
      description: "نمای داده‌های پایه",
      group: "داشبورد",
    },
    {
      label: "ویرایش سفارش",
      href: "/support/orders",
      icon: "pencil",
      description: "اصلاح سفارش ‌ها",
      group: "سفارش‌ها",
    },
    {
      label: "تنظیم لیست قیمت مرجع",
      href: "/support/pricing/reference-price-lists",
      icon: "layers",
      description: "انتخاب مرجع فعال برند",
      group: "قیمت‌گذاری",
    },
    {
      label: "لیست‌های قیمت",
      href: "/support/pricing/generated-price-lists",
      icon: "file-check",
      description: "قیمت‌های داخلی قابل استفاده در سفارش",
      group: "قیمت‌گذاری",
    },
    {
      label: "کالاها",
      href: "/support/products",
      icon: "boxes",
      description: "فهرست و وضعیت کالا",
      group: "مشتریان",
    },
    {
      label: "اختصاص مشتری",
      href: "/support/customer-assignments",
      icon: "users",
      description: "مشتریان سپیدار و کارشناسان",
      group: "مشتریان",
    },
    {
      label: "موجودی فروش",
      href: "/support/product-stock-inventory",
      icon: "boxes",
      description: "کالا و انبار سپیدار",
      group: "موجودی و انبار",
    },
    {
      label: "ردیابی موجودی",
      href: "/support/warehouse/stocks",
      icon: "warehouse",
      description: "کدهای رهگیری و سریال‌ها",
      group: "موجودی و انبار",
    },
    {
      label: "انتقال موجودی",
      href: "/support/stock-transfers",
      icon: "truck",
      description: "درخواست انتقال بین انبارها",
      group: "موجودی و انبار",
    },
    {
      label: "کاربران",
      href: "/support/users",
      icon: "layers",
      description: "کاربران و نقش‌ها",
      group: "تنظیمات",
    },
    {
      label: "تنظیمات سپیدار",
      href: "/support/sepidar-settings",
      icon: "plug-zap",
      description: "اتصال و همگام‌سازی",
      group: "تنظیمات",
    },
    {
      label: "فروشگاه",
      href: "/support/shop",
      icon: "shopping-cart",
      description: "مدیریت فروشگاه سایت",
      group: "فروشگاه",
    },
    {
      label: "محصولات سایت",
      href: "/support/shop/products",
      icon: "package",
      description: "مدیریت محصولات فروشگاه",
      group: "فروشگاه",
    },
    {
      label: "سفارش‌های سایت",
      href: "/support/shop/orders",
      icon: "shopping-cart",
      description: "پیگیری سفارش‌های فروشگاه",
      group: "فروشگاه",
    },
    {
      label: "مجله",
      href: "/support/shop/magazine",
      icon: "file-text",
      description: "مدیریت محتوای مجله",
      group: "فروشگاه",
    },
    {
      label: "مقاله‌ها",
      href: "/support/shop/magazine/posts",
      icon: "file-text",
      description: "لیست مقاله‌های مجله",
      group: "فروشگاه",
    },
    {
      label: "ایجاد مقاله",
      href: "/support/shop/magazine/posts/create",
      icon: "plus-circle",
      description: "ثبت مقاله جدید",
      group: "فروشگاه",
    },
    {
      label: "برندها",
      href: "/support/shop/brands",
      icon: "layers",
      description: "مدیریت برندهای فروشگاه",
      group: "فروشگاه",
    },
    {
      label: "دسته‌بندی‌ها",
      href: "/support/shop/categories",
      icon: "boxes",
      description: "مدیریت دسته‌بندی‌های فروشگاه",
      group: "فروشگاه",
    },
  ],
};
